image: python:3.11

variables:
  CONTAINER_IMAGE: ${CI_PROJECT_PATH}:${CI_COMMIT_SHORT_SHA}

stages:
  - test
  - package
  - doc
  - test-package
  - publish
  - deploy

.tox: &tox
  script:
    - pip install tox
    - tox -e ${TOXENV:-$CI_JOB_NAME}
  stage: test

lint:
  <<: *tox

py3:
  <<: *tox
  artifacts:
    paths:
      - coverage.xml
      - xunit.xml

selenium:
  <<: *tox
  before_script:
    - apt update && apt -y --no-install-recommends install xvfb xauth chromium-driver
  artifacts:
    paths:
      - coverage-selenium.xml
      - xunit-selenium.xml

wrap-and-sort:
  stage: test
  image: buildpack-deps:stable
  script:
  - apt update
  - apt -y --no-install-recommends install devscripts python3-debian
  - CHANGES=$(wrap-and-sort -astN)
  - if [[ ! -z "$CHANGES" ]]; then echo "$CHANGES"; exit 1; fi

trixie:
  <<: *tox

postgresql:
  <<: *tox
  services:
    - postgres:12.2-alpine
  variables:
    TOXENV: py3
    TEST_DATABASE_URI: "postgresql://admin@postgres/test"
    POSTGRES_DB: test
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: ""
    POSTGRES_HOST_AUTH_METHOD: trust

sonar:
  allow_failure: true
  image: sonarsource/sonar-scanner-cli
  needs:
    - py3
    - selenium
  script:
    - sonar-scanner -X -Dsonar.python.coverage.reportPaths=coverage*.xml -Dsonar.python.xunit.reportPaths=xunit*.xml -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.projectVersion=$(git describe) -Dsonar.qualitygate.wait=true
  stage: test
  variables:
    SONAR_PROJECT_BASE_DIR: "${CI_PROJECT_DIR}"

doc:
  <<: *tox
  stage: doc
  needs: []
  dependencies: []
  artifacts:
    paths:
      - .tox/doc/tmp/html
    expire_in: 1 day


package:dsc:
  stage: package
  needs: []
  image: buildpack-deps:unstable
  variables:
    GIT_DEPTH: 50  # GitLab runner will fetch last 50 commits
  script: 
    - rm -f ../*.debian.tar.xz ../*.orig.tar.xz ../*.dsc
    # Install build dependencies
    - apt -U -y --no-install-recommends install tox
    - apt build-dep -y --no-install-recommends -P nocheck,nodoc .
    # Update changelog for automatic build
    - git config user.email "$GITLAB_USER_EMAIL"
    - git config user.name "$GITLAB_USER_NAME"
    - (tox -e changelog && git commit -m "automatic build" CHANGELOG.md debian/changelog) || true
    # Create original tarball ".orig.tar.xz"
    - debian/rules gentarball
    # Build debian source package ".dsc"
    - dpkg-buildpackage -S --no-check-builddeps
    - mkdir -p ./dist/
    - mv ../*.debian.tar.xz ../*.orig.tar.xz ../*.dsc ./dist/
  artifacts:
    paths:
      - ./dist/*

package:deb:
  stage: package
  needs: 
    - package:dsc
  image: buildpack-deps:$DIST
  variables:
     GIT_STRATEGY: none  # GitLab runner will NOT clone/fetch repo
  parallel:
    matrix:
      - DIST: [forky]
  script: |
    set -x
    set -e
    rm -f *.deb
    # Add APT repo ofr cherrypy-foundation dependencies
    wget -O /etc/apt/keyrings/ikus-keyring.asc https://www.ikus-soft.com/archive/public.key
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/ikus-keyring.asc] https://nexus.ikus-soft.com/repository/apt-dev-$DIST/ $DIST-dev main" > /etc/apt/sources.list.d/ikus.list
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/ikus-keyring.asc] https://nexus.ikus-soft.com/repository/apt-release-$DIST/ $DIST main" >> /etc/apt/sources.list.d/ikus.list
    # Install build dependencies
    apt update
    apt -y --no-install-recommends install lintian
    ls -1 ./dist/*.dsc | while read -r FILE
    do
      rm -rf builddir
      dpkg-source -x ${FILE} builddir/
      pushd builddir/
      apt build-dep -y --no-install-recommends .
      # Build debian binary package ".deb"
      dpkg-buildpackage -b
      popd
      lintian --info --display-info --pedantic *.deb ${FILE}
      mkdir -p ./dist/${DIST}
      mv *.deb ./dist/${DIST}/
    done
  artifacts:
    paths:
      - ./dist/*

test-package:deb:
  stage: test-package
  image: buildpack-deps:unstable
  needs: ["package:deb"]
  parallel:
    matrix:
    - DIST: [forky]
  script:
    - apt update
    - apt install -y apt-transport-https ca-certificates lsb-release gpg
    - wget -O /etc/apt/keyrings/minarca-keyring.asc https://www.ikus-soft.com/archive/minarca/public.key
    - echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/minarca-keyring.asc] https://nexus.ikus-soft.com/repository/apt-dev-$DIST/ $DIST-dev main" > /etc/apt/sources.list.d/minarca.list
    - echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/minarca-keyring.asc] https://nexus.ikus-soft.com/repository/apt-release-$DIST/ $DIST main" >> /etc/apt/sources.list.d/minarca.list
    - apt update
    - apt -y --no-install-recommends install ./dist/$DIST/bfh-ssp_*_all.deb
    - bfh-ssp --version
    - (bfh-ssp &)
    - timeout 60 bash -c 'until curl --silent http://localhost:8080; do sleep 1; done'

publish:dsc:
  needs:
    - package:dsc
  only:
    variables:
      - $NEXUS_USR
      - $NEXUS_PWD
  script: |
    set -e
    set -x
    # Loop on dsc files
    ls -1 ./dist/*.dsc | while read -r FILE
    do
      # Define where to send files.
      FILENAME="${FILE##*/}" 
      PKGNAME="${FILENAME%%_*}"
      TMP="${FILENAME#*_}"
      VERSION="${TMP%.dsc}"
      ARCHIVE_URL="$NEXUS_URL/repository/archive/debian/$PKGNAME/$VERSION"
      # For each file in dsc, upload it to nexus
      grep -A99 "^Files:" "$FILE" | grep "^ " | awk '{print $3}' | while read -r ASSET
      do
        curl --fail -u "$NEXUS_USR:$NEXUS_PWD" \
          --upload-file "./dist/$ASSET" \
          "$ARCHIVE_URL/$(basename "$ASSET")"
      done
      # Upload the .dsc itself
      curl --fail -u "$NEXUS_USR:$NEXUS_PWD" \
        --upload-file "$FILE" \
        "$ARCHIVE_URL/$(basename "$FILE")"
    done
  stage: publish

publish:deb:
  needs:
    - package:deb
  only:
    variables:
      - $NEXUS_USR
      - $NEXUS_PWD
  parallel:
    matrix:
      - DIST: [forky]
  script: |
    set -e
    set -x
    if [[ "$CI_COMMIT_TAG" == *.+([0-9]) ]]; then
      APT_URL="$NEXUS_URL/repository/apt-release-${DIST}/"
      APT_COMPONENT=${DIST}
    else
      APT_URL="$NEXUS_URL/repository/apt-dev-${DIST}/"
      APT_COMPONENT=${DIST}-dev
    fi
    # Upload binaries
    ls -1 ./dist/$DIST/*.deb | while read -r FILE
    do
      curl --fail -u "$NEXUS_USR:$NEXUS_PWD" -H "Content-Type: multipart/form-data" --data-binary "@$FILE" "$APT_URL"
      sleep 2
      ARCH=$(echo "$FILE" | grep -oP '(?<=_)[^_]+(?=\.deb$)')
      curl --fail "${APT_URL}dists/$APT_COMPONENT/main/binary-${ARCH}/Packages" | grep "$(basename $FILE)"
    done
  stage: publish

publish:doc:
  stage: publish
  only:
    variables:
      - $NEXUS_USR
      - $NEXUS_PWD
      - $NEXUS_URL
  needs:
    - doc
  script:
    - pip install setuptools-scm
    - export VERSION=$(python -m setuptools_scm)
    - cd .tox/doc/tmp/html
    # publish to nexus
    - find * -type f -exec curl --fail -u "$NEXUS_USR:$NEXUS_PWD" --upload-file "{}" $NEXUS_URL/repository/archive/udb/$VERSION/doc/{} \;

deploy:dev:
  allow_failure: True
  environment:
    name: dev
    url: https://udb-demo.ikus-soft.com/
  needs:
    - publish:deb
  image: registry.gitlab.com/finestructure/pipeline-trigger
  script:
    - apk update && apk add git
    - export DEB_VERSION=$(ls -1 dist/forky/udb_*_all.deb | cut -d '_' -f 2)
    - echo DEB_VERSION=$DEB_VERSION
    # Trigger ansible-config pipeline
    - trigger -a "$ANSIBLE_PIPELINE_GITLAB_API_TOKEN" -t master -e "UDB_VERSION=$DEB_VERSION" -p 36bae86778d901fc6b2d6453a41844 18716492
  stage: deploy
  variables:
    GIT_STRATEGY: none
