[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
skip-string-normalization = "True"

[tool.isort]
profile = "black"
line_length = 120

[tool.djlint]
indent=2

[tool.setuptools_scm]