[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "udb"
authors = [
    {name = "Patrik Dufresne", email = "patrik@ikus-soft.com"},
]
description = "Web application used to manage records to configure enterprise network with ansible-playbook."
readme = "README.md"
requires-python = ">=3.10, <4"
license = {text = "GPLv3"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: CherryPy",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "apscheduler",
    "argon2-cffi>=18.3.0",
    "babel",
    "CherryPy>18",
    "cherrypy-foundation>=1.12.0,<2",
    "cheroot<11",
    "configargparse",
    "email_validator",
    "Jinja2",
    "jinjax @ git+https://github.com/ikus060/jinjax@patrik-multi-thread-hotfix",
    "ldap3",
    "pytz",
    "requests",
    "ujson",
    "sqlalchemy>=2,<3",
    "validators",
    "WTForms>=2.2.1",
    "zxcvbn>=4.4.27",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "black==25.9.0",
    "djlint==1.36.4",
    "flake8",
    "flake8-copyright",
    "isort==7.0.0",
]
test = [
    "html5lib",
    "parameterized",
    "pytest",
    "selenium",
]

[project.scripts]
udb = "udb.main:main"

[project.urls]
Homepage = "https://gitlab.com/ikus-soft/udb"

[tool.black]
line-length = 120
skip-string-normalization = "True"

[tool.isort]
profile = "black"
line_length = 120

[tool.djlint]
indent=2
custom_html = """
  cf:Datatable,\
  cf:Field,\
  cf:Fields,\
  cf:Flash,\
  cf:Icon
"""

[tool.setuptools_scm]
version_scheme = "no-guess-dev"

[tool.git-changelog]
output = "CHANGELOG.md"
template = "keepachangelog"
convention = "linux"
sections = [":all:"]  # Include all sections
include-all = true  # Include all random msg
in-place = 1
jinja_context = { debian_package_name = "udb", debian_version_suffix = "-1" }
